#!/usr/bin/env node

'use strict';

const cp = require('child_process');
const res = require('path').resolve;
const {argv} = process;

if (argv.length < 3) {
  console.error('Usage: $ ./migrate/latest [bcoin-prefix]');
  console.error('Example: $ ./migrate/latest ~/.bcoin');
  process.exit(1);
  return;
}

function exec(file, ...args) {
  try {
    const result = cp.spawnSync(file, args, {
      stdio: 'inherit',
      env: process.env,
      maxBuffer: -1 >>> 0,
      windowsHide: true
    });
    if (result.error)
      console.error(result.error.message);
  } catch (e) {
    console.error(e.message);
  }
}

const node = argv[0];
const prefix = argv[2];

exec(node, res(__dirname, 'chaindb3to4.js'), res(prefix, 'chain'));
exec(node, res(__dirname, 'chaindb3to4.js'), res(prefix, 'spvchain'));
exec(node, res(__dirname, 'chaindb4to5.js'), res(prefix, 'chain'));
exec(node, res(__dirname, 'chaindb5to6.js'), res(prefix, 'chain'));
exec(node, res(__dirname, 'walletdb6to7.js'), res(prefix, 'wallet'));
